<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="TSS.Core.Mapping">
      <HintPath>lib\TSS.Core.Mapping.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="TSS.Core.Mapping">
      <HintPath>lib\TSS.Core.Mapping.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
