<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.EntityFrameworkCore">
      <HintPath>lib\Microsoft.EntityFrameworkCore.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.Relational">
      <HintPath>lib\Microsoft.EntityFrameworkCore.Relational.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore.SqlServer">
      <HintPath>lib\Microsoft.EntityFrameworkCore.SqlServer.dll</HintPath>
    </Reference>
    <Reference Include="TSS.Core.Persistence">
      <HintPath>lib\TSS.Core.Persistence.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TSS.Audit.Common\TSS.Audit.Common.csproj" />
    <ProjectReference Include="..\TSS.Audit.Domain\TSS.Audit.Domain.csproj" />
    <ProjectReference Include="..\TSS.Audit.Persistence\TSS.Audit.Persistence.csproj" />
  </ItemGroup>
</Project>