<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Autofac">
      <HintPath>lib\Autofac.dll</HintPath>
    </Reference>
    <Reference Include="Autofac.Extensions.DependencyInjection">
      <HintPath>lib\Autofac.Extensions.DependencyInjection.dll</HintPath>
    </Reference>
    <Reference Include="DocumentFormat.OpenXml">
      <HintPath>lib\DocumentFormat.OpenXml.dll</HintPath>
    </Reference>
    <Reference Include="ExpressMapper">
      <HintPath>lib\ExpressMapper.dll</HintPath>
    </Reference>
    <Reference Include="FluentValidation">
      <HintPath>lib\FluentValidation.dll</HintPath>
    </Reference>
    <Reference Include="IdentityServer4.AccessTokenValidation">
      <HintPath>lib\IdentityServer4.AccessTokenValidation.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore">
      <HintPath>lib\Microsoft.AspNetCore.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Authentication">
      <HintPath>lib\Microsoft.AspNetCore.Authentication.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Authorization">
      <HintPath>lib\Microsoft.AspNetCore.Authorization.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Cors">
      <HintPath>lib\Microsoft.AspNetCore.Cors.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Diagnostics">
      <HintPath>lib\Microsoft.AspNetCore.Diagnostics.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Hosting">
      <HintPath>lib\Microsoft.AspNetCore.Hosting.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Hosting.Abstractions">
      <HintPath>lib\Microsoft.AspNetCore.Hosting.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Http.Abstractions">
      <HintPath>lib\Microsoft.AspNetCore.Http.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Http.Features">
      <HintPath>lib\Microsoft.AspNetCore.Http.Features.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Mvc">
      <HintPath>lib\Microsoft.AspNetCore.Mvc.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Mvc.Abstractions">
      <HintPath>lib\Microsoft.AspNetCore.Mvc.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Mvc.Core">
      <HintPath>lib\Microsoft.AspNetCore.Mvc.Core.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Mvc.Formatters.Json">
      <HintPath>lib\Microsoft.AspNetCore.Mvc.Formatters.Json.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.AspNetCore.Mvc.ViewFeatures">
      <HintPath>lib\Microsoft.AspNetCore.Mvc.ViewFeatures.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.EntityFrameworkCore">
      <HintPath>lib\Microsoft.EntityFrameworkCore.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Configuration.Abstractions">
      <HintPath>lib\Microsoft.Extensions.Configuration.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Configuration.Binder">
      <HintPath>lib\Microsoft.Extensions.Configuration.Binder.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <HintPath>lib\Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyModel">
      <HintPath>lib\Microsoft.Extensions.DependencyModel.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Primitives">
      <HintPath>lib\Microsoft.Extensions.Primitives.dll</HintPath>
    </Reference>
    <Reference Include="NPoco">
      <HintPath>lib\NPoco.dll</HintPath>
    </Reference>
    <Reference Include="NSwag.AspNetCore">
      <HintPath>lib\NSwag.AspNetCore.dll</HintPath>
    </Reference>
    <Reference Include="NSwag.Core">
      <HintPath>lib\NSwag.Core.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>lib\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="Serilog">
      <HintPath>lib\Serilog.dll</HintPath>
    </Reference>
    <Reference Include="Serilog.AspNetCore">
      <HintPath>lib\Serilog.AspNetCore.dll</HintPath>
    </Reference>
    <Reference Include="Serilog.Settings.Configuration">
      <HintPath>lib\Serilog.Settings.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="StackifyMiddleware">
      <HintPath>lib\StackifyMiddleware.dll</HintPath>
    </Reference>
    <Reference Include="TSS.Core.Persistence">
      <HintPath>lib\TSS.Core.Persistence.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Packaging">
      <HintPath>lib\System.IO.Packaging.dll</HintPath>
    </Reference>
    <Reference Include="NSwag.SwaggerGeneration.WebApi">
      <HintPath>lib\NSwag.SwaggerGeneration.WebApi.dll</HintPath>
    </Reference>
    <Reference Include="TSS.Core.Mapping">
      <HintPath>lib\TSS.Core.Mapping.dll</HintPath>
    </Reference>
    <Reference Include="NJsonSchema">
      <HintPath>lib\NJsonSchema.dll</HintPath>
    </Reference>
    <Reference Include="Serilog.Sinks.Literate">
      <HintPath>lib\Serilog.Sinks.Literate.dll</HintPath>
    </Reference>
    <Reference Include="Serilog.Sinks.RollingFileAlternate">
      <HintPath>lib\Serilog.Sinks.RollingFileAlternate.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TSS.Audit.Common\TSS.Audit.Common.csproj" />
    <ProjectReference Include="..\TSS.Audit.DTOs\TSS.Audit.DTOs.csproj" />
    <ProjectReference Include="..\TSS.Audit.ExternalServicesClients\TSS.Audit.ExternalServicesClients.csproj" />
    <ProjectReference Include="..\TSS.Audit.ExternalServicesClients.Abstractions\TSS.Audit.ExternalServicesClients.Abstractions.csproj" />
    <ProjectReference Include="..\TSS.Audit.Mapping\TSS.Audit.Mapping.csproj" />
    <ProjectReference Include="..\TSS.Audit.Mapping.ExpressMapper\TSS.Audit.Mapping.ExpressMapper.csproj" />
    <ProjectReference Include="..\TSS.Audit.Persistence\TSS.Audit.Persistence.csproj" />
    <ProjectReference Include="..\TSS.Audit.Persistence.EFCore\TSS.Audit.Persistence.EFCore.csproj" />
    <ProjectReference Include="..\TSS.Audit.Persistence.NPoco\TSS.Audit.Persistence.NPoco.csproj" />
    <ProjectReference Include="..\TSS.Audit.ReadServices\TSS.Audit.ReadServices.csproj" />
    <ProjectReference Include="..\TSS.Audit.Resources\TSS.Audit.Resources.csproj" />
    <ProjectReference Include="..\TSS.Audit.WriteServices\TSS.Audit.WriteServices.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.AspNetCore.Authentication.JwtBearer">
      <HintPath>lib\Microsoft.AspNetCore.Authentication.JwtBearer.dll</HintPath>
    </Reference>
    <Reference Include="IdentityModel.AspNetCore.OAuth2Introspection">
      <HintPath>lib\IdentityModel.AspNetCore.OAuth2Introspection.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Serilog.Extensions.Logging">
      <HintPath>lib\Serilog.Extensions.Logging.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="NSwag.SwaggerGeneration">
      <HintPath>lib\NSwag.SwaggerGeneration.dll</HintPath>
    </Reference>
    <Reference Include="NSwag.Annotations">
      <HintPath>lib\NSwag.Annotations.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>



